### ISSUE TITLE
Clipper implementation correct?

### ISSUE THREAD

**Issue by iamgroot42** [Gunjan108/robust-ecoc#1]
Comments in the code say `Only active at training time since it is a regularization layer.`
However, the call:

`return K.in_train_phase(augmented, augmented, training=training)`

basically means that it's called in both cases (training=True or False). Is this intended behavior?

**Comment by iamgroot42** [comment]
Same issue with Grayscaler.py

**Comment by Gunjan108** [comment]
yes, this is the intended behavior. (code / comments are a bit sloppy, apologies for that).

essentially the idea is we want to apply clipping (and grayscaling) at all times.
