### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by antonyalexos** [Gunjan108/robust-ecoc#2]
Hey man, it would be very useful for us to know the requirements of the libraries. You only mention python 3.6 and CleverHans 3.0.1. What about TF and keras? It seems that there exists a problem with tf 1.14 and afterwards.
The DataAugmenter.py doesn't work.

**Comment by Gunjan108** [comment]
> Hey man, it would be very useful for us to know the requirements of the libraries. You only mention python 3.6 and CleverHans 3.0.1. What about TF and keras? It seems that there exists a problem with tf 1.14 and afterwards.
> The DataAugmenter.py doesn't work.

Hi , the version of TF is: 1.9.0.  Keras is integrated into this version of TF and that's what was used. thanks!

**Comment by antonyalexos** [comment]
Hello, thanks for the clarification. Although I had solved the problem a couple of months back but I just forgot to close the issue. I can reproduce the results of the paper with your code so it's all good. Nice work!
